id: I48848E54
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T04:08:28+00:00'
last_modified: '2022-06-08T16:12:46.552574+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS16854
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་ཚད་མ་གྲུབ་པའི་ལེའུའི་མཐའ་དཔྱོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    88CA:
      image_group_id: I8LS16873
      title: Volume 1 of tshad ma rnam 'grel gyi tshad ma grub pa'i le'u'i mtha' dpyod/
      total_pages: 1011
      order: 1
      base_file: 88CA.txt
    34F1:
      image_group_id: I8LS16874
      title: Volume 2 of tshad ma rnam 'grel gyi tshad ma grub pa'i le'u'i mtha' dpyod/
      total_pages: 716
      order: 2
      base_file: 34F1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
